# Project Configuration
config:
  project_name: "libvpx"
  program_language: "c++"
  fuzz_projects_dir: "/home/xuhanxiang/project/CKGFuzzer/fuzzing_llm_engine/external_database/libvpx/"
  work_dir: "/home/xuhanxiang/project/CKGFuzzer/"
  shared_dir: "/home/xuhanxiang/project/CKGFuzzer/docker_shared/"
  report_target_dir: "/linux/src/libvpx"
  time_budget: "1s"

  headers:
    - <vpx/vp8dx.h>
    - <vpx/vp8cx.h>
    - <vpx/vpx_decoder.h>
    - <stdlib.h>
    - <string.h>
    - <stdint.h>
    - <sstream>
  


llm_embedding:


# DeepSeek Analyzer Configuration
llm_analyzer:
  api_key: "sk-e035cc88b86044a19d2356b288ad452b"
  model: "deepseek-chat"
  #proxy: "http://<ip>:<port>"
  base_url: "https://api.deepseek.com/v1"
  temperature: 1.0


# DeepSeek Coder Configuration
llm_coder:
  api_key: "sk-e035cc88b86044a19d2356b288ad452b"
  model: "deepseek-coder"
  #proxy: "http://<ip>:<port>"
  base_url: "https://api.deepseek.com/v1"
  temperature: 0.7

